global:
  scrape_interval: 10s
  evaluation_interval: 30s
scrape_configs:
  - job_name: 'clientforge-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
